# nginx.conf
user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;
    server_tokens off;

    # Basic gzip (optional)
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_types text/plain text/css application/json application/javascript application/xml+rss image/svg+xml;

    server {
        listen 80;
        server_name *;

        # Root of your static site
        root /usr/share/nginx/html;
        index index.html index.htm;

        # Serve static assets efficiently
        location / {
            try_files $uri $uri/ =404;
        }

        location = /env.js {
            add_header Cache-Control "no-store";
        }
    }
}